# Stage 1: Temporary image for building react
FROM node:17-alpine AS react-build-stage
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY public ./public
COPY src ./src
COPY *.json /app/
RUN ["npm", "install"]
RUN ["npm", "run", "build"]


# Stage 2: Build image for nginx
FROM nginx:stable-alpine
COPY --from=react-build-stage /app/build /usr/share/nginx/html
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf
