version: "3.3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    env_file:
      - ./api/.env  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    environment:
      - VIRTUAL_HOST=nyayumiscatcafe.com
      - LETSENCRYPT_HOST=nyayumiscatcafe.com
